services:
  - type: web
    name: lista-compras-php
    env: docker
    plan: free
    autoDeploy: true
    dockerContext: .
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /
